### PR TITLE
Refactor NrelService

### PR DESCRIPTION
**Pull request by chadmetcalf**
Not really for merging....just a jumping off point for our discussion tomorrow about POROs and OOD.

### CODE REVIEW

**Comment by alishersadikov** [comment]
okay, I see!

**Comment by chadmetcalf** [comment]
Have you been working on anything lately? I need to start working on some side projects so that you can return the code reviewing favor.

**Comment by alishersadikov** [comment]
Sorry, I have been working on two other school projects and therefore got a little busy. I am working on applying your suggestions will have a PR soon. I am really curious to see your side projects and am sure will learn a ton from them.

**Comment by alishersadikov** [comment]
Brought back memories.

**Pull request closed without merging**
